import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../Navbar';
import Footer from '../Footer';

export default function TermsPage() {
  const sections = [
    {
      title: "1. Terms of Use",
      content: "By accessing and using RemyAI, you accept and agree to be bound by the terms and provision of this agreement."
    },
    {
      title: "2. User Account",
      content: "You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account."
    },
    {
      title: "3. Privacy",
      content: "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your personal information."
    },
    {
      title: "4. Content",
      content: "All recipes and content generated by RemyAI are for informational purposes only. Users should exercise caution and common sense when following recipe suggestions."
    },
    {
      title: "5. Intellectual Property",
      content: "The RemyAI service and its original content, features, and functionality are owned by RemyAI and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws."
    },
    {
      title: "6. User Guidelines",
      content: "Users agree not to misuse the service or help anyone else do so. This includes attempting to access the service through unauthorized means."
    },
    {
      title: "7. Modifications",
      content: "We reserve the right to modify or replace these terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect."
    },
    {
      title: "8. Disclaimer",
      content: "The service is provided 'as is' without any warranties, expressed or implied. RemyAI does not warrant that the service will be uninterrupted or error-free."
    }
  ];

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow pt-24 pb-16 px-4 bg-gradient-to-br from-orange-50 to-red-50">
        <div className="max-w-4xl mx-auto">
          <Link 
            to="/" 
            className="inline-flex items-center text-gray-600 hover:text-primary transition-colors mb-8"
          >
            <ArrowLeft className="w-5 h-5 mr-1" />
            <span>Back to Home</span>
          </Link>

          <div className="bg-white rounded-xl shadow-md p-8">
            <h1 className="text-4xl font-heading font-bold text-gray-900 mb-8">
              Terms of Service
            </h1>

            <div className="prose prose-lg max-w-none">
              <p className="text-gray-600 mb-8">
                Last updated: March 15, 2024
              </p>

              {sections.map((section, index) => (
                <div key={index} className="mb-8">
                  <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">
                    {section.title}
                  </h2>
                  <p className="text-gray-600">
                    {section.content}
                  </p>
                </div>
              ))}

              <div className="mt-12 p-6 bg-gray-50 rounded-lg">
                <h3 className="text-xl font-heading font-bold text-gray-900 mb-4">
                  Contact Us
                </h3>
                <p className="text-gray-600">
                  If you have any questions about these Terms, please contact us at{' '}
                  <a 
                    href="mailto:legal@remyai.com"
                    className="text-primary hover:text-primary-hover"
                  >
                    legal@remyai.com
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}